- name: check dir /data/open-falcon
  stat:
    path: /data/open-falcon
  ignore_errors: True
  register: result

- name: meta end_play
  meta: end_play
  when: result.stat.exists == true

- name: mkdir /data/open-falcon
  file:
    state: directory
    path: /data/open-falcon

- name: copy agent package to dest hosts and unarchive agent package
  unarchive:
    copy: yes
    src: falcon-agent-qcloud.tgz
    dest: /data/open-falcon/

- name: template cfg.json
  template:
    src: cfg.json
    dest: /data/open-falcon/agent/config/cfg.json

- name: start open-falcon
  shell: nohup ./open-falcon start agent
  args:
    chdir: /data/open-falcon/
